window.PRODUCTS_DATA = [
  {
    "id": "dummy-13",
    "nome": "Dummy 13",
    "linha": "Colecionável",
    "categoria": "Articulado",
    "tipo": "Display",
    "preco": 50,
    "sku": "PD3D-COL-001",
    "imagem": "/produtos/dummy-13.webp",
    "selo": "",
    "ativo": true,
    "sazonal": false,
    "destaque": true
  },
  {
    "id": "blastoise",
    "nome": "Blastoise",
    "linha": "Geek Premium",
    "categoria": "Personagem",
    "tipo": "Display",
    "preco": 280,
    "sku": "PD3D-PER-004",
    "imagem": "/produtos/blastoise.webp",
    "selo": "",
    "ativo": true,
    "sazonal": false,
    "destaque": true
  },
  {
    "id": "naruto",
    "nome": "Naruto",
    "linha": "Geek Premium",
    "categoria": "Personagem",
    "tipo": "Display",
    "preco": 70,
    "sku": "PD3D-PER-011",
    "imagem": "/produtos/naruto.webp",
    "selo": "",
    "ativo": true
  },
  {
    "id": "cubo-engrenagem",
    "nome": "Cubo Engrenagem",
    "linha": "Sensorial",
    "categoria": "Fidget",
    "tipo": "Articulado",
    "preco": 40,
    "sku": "PD3D-CUBO-ENGRENAGEM",
    "imagem": "/produtos/cubo-engrenagem.webp",
    "selo": "",
    "ativo": true
  },
  {
    "id": "cubogami",
    "nome": "Cubogami",
    "linha": "Sensorial",
    "categoria": "Fidget",
    "tipo": "Articulado",
    "preco": 30,
    "sku": "PD3D-CUBOGAMI",
    "imagem": "/produtos/cubogami.webp",
    "selo": "",
    "ativo": true
  },
  {
    "id": "jogo-da-forca",
    "nome": "Jogo da Forca",
    "linha": "Educativo",
    "categoria": "Jogo",
    "tipo": "Interativo",
    "preco": 35,
    "sku": "PD3D-JOGO-DA-FORCA",
    "imagem": "/produtos/jogo-da-forca.webp",
    "selo": "",
    "ativo": true
  },
  {
    "id": "patolino-shopping",
    "nome": "Patolino (Calça de Shopping)",
    "linha": "Geek",
    "categoria": "Personagem",
    "tipo": "Display",
    "preco": 70,
    "sku": "PD3D-PATOLINO-SHOPPING",
    "imagem": "/produtos/patolino-shopping.webp",
    "selo": "",
    "ativo": true
  }
];
